trigger:
  branches:
    include:
      - main  # Change this to your default branch if it's different

pool:
  name: 'Default'  # Specify your self-hosted agent pool if you are using it

steps:
  # Install .NET SDK (change version as needed)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'  # Adjust to the version of .NET you are using
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Restore NuGet packages
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.sln'  # Restores all solutions in the repository

  # Build the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'  # Builds all solutions in the repository
      arguments: '/p:Configuration=Release'

  # Publish the project
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      deleteExistingFiles: true
      publishDirectory: $(Build.ArtifactStagingDirectory)
      arguments: '--configuration Release'

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)  # Path where build output is stored
      ArtifactName: 'fsifat'  # Name of the artifact
      publishLocation: 'Container'
