trigger: none  # Trigger manually or from a build pipeline

pool:
  name: 'SelfHostedPool'

jobs:
- job: DeployToIIS
  displayName: 'Deploy to IIS'
  pool:
    name: 'SelfHostedPool'

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'fsifat'  # Replace with your artifact name
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(System.ArtifactsDirectory)/fsifat/**/*.zip'
      destinationFolder: 'C:\Deploy\MovieMVC\Extracted'
      cleanDestinationFolder: true
      overwriteExistingFiles: true

  - task: PowerShell@2
    displayName: 'Deploy to IIS'
    inputs:
      targetType: 'inline'
      script: |
        # Define the source and destination
        $source = "C:\Deploy\MovieMVC\Extracted"
        $destination = "C:\inetpub\wwwroot\MovieMVC"
        
        # Copy the extracted files to the IIS folder
        Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

        Write-Host "Deployment complete."
